### PR TITLE
Update Apache to 2.4.25

### PR DESCRIPTION
**Pull request by photodude**
- Apache update info
  - http://www.apache.org/dist/httpd/Announcement2.4.html
~~- Also update dependency vcredist2012 to 11.0.61031~~
  ~~- https://chocolatey.org/packages/vcredist2012~~
- add dependency chocolatey-core.extension

download files for windows
- http://www.apachehaus.com/cgi-bin/download.plx
- https://www.apachelounge.com/download/

/cc @rgra @AdmiringWorm @ferventcoder

### CODE REVIEW

**Comment by photodude** [comment]
I've never updated a package, if there are additional items needing to be changed to make this work please let me know.

**Comment by photodude** [comment]
Any comment on possibly merging this or getting a different PR opened to updated this package?

/cc @rgra @AdmiringWorm @ferventcoder

**Comment by rgra** [comment]
@photodude I'd be happy to give your admin rights on the choco package to update it yourselves if you like to? At the moment I don't have the time to do it myself.

**Comment by photodude** [comment]
@rgra Thank you for the offer, I'm honored you would consider adding me as an admin. But, I'm not sure I know what I'm doing with package updates (I'm a total choco noob when it comes to creating/updating packages, I've only read info on what might need to be done) maybe @AdmiringWorm or @ferventcoder would be willing to help or be willing to suggest someone who would be better qualified to evaluate this PR or update this package.

**Comment by laukstein** [comment]
Any ETA for landing this package?

**Comment by photodude** [comment]
@laukstein we need someone to join in as an admin who is competent at creating/updating packages while the Repo owner is unable to commit the time. I'm asked for help from the community, but no one has stepped forward. https://groups.google.com/d/msg/chocolatey/NNEUFj4IfXA/BGYgEuILAwAJ

/cc @rgra @AdmiringWorm @ferventcoder

**Comment by ferventcoder** [comment]
I believe getting this set up and migrated over to the [core maintainers team repo](https://github.com/chocolatey/chocolatey-coreteampackages) may be more beneficial - they have an AU already set up and it can keep the package up to date. I am definitely out as folks are migrating my packages into that core team repo now as I have lots of things on my plate (all related to aspects of the Chocolatey ecosystem), and package updates tend to suffer if they are not already automated as they fall down as compared to the priority of other parts. 

As Apache is one of those essential packages for the community, I don't see it being an issue if you start the process of migrating it - https://github.com/chocolatey/chocolatey-coreteampackages

**Comment by photodude** [comment]
Issue opened for the migration to the core repo with AU
https://github.com/chocolatey/chocolatey-coreteampackages/issues/728

**Comment by photodude** [comment]
Closing as this has been migrated to the core team and has automatic updates for the version now

**Pull request closed without merging**
